"""
plot_psd_vs_feedback.py

Reads PSD CSV files and summary data generated by linewidth_vs_dbr_coupling_scan.py.
Generates a perfectly aligned 2-panel plot:
  - Top Panel: Laser Linewidth (MHz) vs. Feedback Strength (dB).
  - Bottom Panel: Optical PSD heatmap (dB) vs. Feedback Strength (dB) (+/- 0.5 GHz).

Features:
  - Unified filename formatting (matches psd_current_9.0mA_... export convention).
  - Robust file existence checking.
  - Fewer interpolation points (400 points) for raw, un-smeared features.
  - Truncated at -47 dB feedback cutoff.
  - Pixel-aligned X-axes between top and bottom panels.
  - Replot support via .npz cache.

Usage:
    python plot_psd_vs_feedback.py [folder_path] [--freq_range_ghz 0.5] [--max_feedback_db -47.0] [--replot]
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable


def get_psd_filename(current, coupling):
    """Generate standardized PSD filename handling both int and float current types."""
    current_val = float(current)
    # Checks if current is whole number (e.g. 9.0) vs decimal (e.g. 9.5)
    if current_val.is_integer():
        curr_str = f"{current_val:.1f}"  # Produces '9.0'
    else:
        curr_str = f"{current_val}"
    
    return f"psd_current_{curr_str}mA_coupling_{coupling:.6e}.csv"


def load_psd_raw(filepath):
    """
    Load a PSD CSV file safely, dropping header text and NaN rows.
    Returns (freq_raw, power_dB_raw).
    """
    try:
        df = pd.read_csv(filepath, comment='#').dropna()
    except Exception:
        return np.array([]), np.array([])

    freq_s = pd.to_numeric(df.iloc[:, 0], errors='coerce')
    power_s = pd.to_numeric(df.iloc[:, 1], errors='coerce')

    valid_mask = freq_s.notna() & power_s.notna()
    freq = freq_s[valid_mask].to_numpy(dtype=np.float64)
    power = power_s[valid_mask].to_numpy(dtype=np.float64)

    # Ensure strictly ascending frequency order
    if len(freq) > 1 and freq[0] > freq[-1]:
        freq = freq[::-1]
        power = power[::-1]

    return freq, power


def process_data(folder, freq_range_ghz=0.5, max_feedback_db=-47.0, n_points=400):
    """
    Load summary CSV and all PSD CSVs, filter entries >= max_feedback_db,
    and build aligned arrays using a coarse, un-averaged grid (n_points=400).
    """
    summary_path = os.path.join(folder, "summary_linewidth_vs_coupling.csv")
    if not os.path.isfile(summary_path):
        raise FileNotFoundError(f"Cannot find summary file: {summary_path}")

    summary = pd.read_csv(summary_path)

    currents = summary["current_mA"].values
    couplings = summary["coupling"].values
    feedback_dB = summary["feedback_strength_dB"].values
    linewidth_MHz = summary["linewidth_MHz"].values

    # Filter non-finite feedback runs AND enforce cutoff at max_feedback_db (-47 dB)
    valid_mask = np.isfinite(feedback_dB) & np.isfinite(linewidth_MHz) & (feedback_dB >= max_feedback_db)
    currents = currents[valid_mask]
    couplings = couplings[valid_mask]
    feedback_dB = feedback_dB[valid_mask]
    linewidth_MHz = linewidth_MHz[valid_mask]

    if len(feedback_dB) == 0:
        raise RuntimeError(f"No valid entries found >= {max_feedback_db} dB in summary CSV.")

    # Sort runs by feedback strength (ascending: weakest/most negative feedback first)
    sort_idx = np.argsort(feedback_dB)
    feedback_sorted = feedback_dB[sort_idx]
    linewidth_sorted = linewidth_MHz[sort_idx]
    currents_sorted = currents[sort_idx]
    couplings_sorted = couplings[sort_idx]

    # ------------------------------------------------------------------
    # 1. Determine unperturbed reference peak frequency
    # ------------------------------------------------------------------
    ref_freq_raw = None
    ref_power_raw = None
    ref_feedback_used = None

    for c, k, fb in zip(currents_sorted, couplings_sorted, feedback_sorted):
        psd_filename = get_psd_filename(c, k)
        psd_path = os.path.join(folder, psd_filename)
        
        # Fallback check in case file was saved without trailing .0
        if not os.path.isfile(psd_path):
            fallback_filename = f"psd_current_{int(c)}mA_coupling_{k:.6e}.csv" if float(c).is_integer() else psd_filename
            psd_path = os.path.join(folder, fallback_filename)

        if os.path.isfile(psd_path):
            freq_test, power_test = load_psd_raw(psd_path)
            if len(freq_test) > 10:
                ref_freq_raw = freq_test
                ref_power_raw = power_test
                ref_feedback_used = fb
                break

    if ref_freq_raw is None:
        raise FileNotFoundError(f"No valid PSD CSV files found in directory: {folder}")

    # Detect unit conversion factor to GHz
    total_span = np.abs(ref_freq_raw[-1] - ref_freq_raw[0])
    to_GHz = 1e3 if total_span < 100 else 1e-3  # Converts THz or MHz -> GHz

    ref_peak_idx = np.argmax(ref_power_raw)
    absolute_zero_freq = ref_freq_raw[ref_peak_idx]

    print(f"Reference run selected: {ref_feedback_used:.2f} dB feedback")
    print(f"Unperturbed peak frequency: {absolute_zero_freq:.6f} (Native units)")

    # ------------------------------------------------------------------
    # 2. Build minimal common offset grid (n_points = 400)
    # ------------------------------------------------------------------
    freq_offset_GHz = np.linspace(-freq_range_ghz, freq_range_ghz, n_points)

    # ------------------------------------------------------------------
    # 3. Interpolate each existing spectrum relative to absolute_zero_freq
    # ------------------------------------------------------------------
    psd_columns_dB = []
    valid_fb_list = []
    valid_lw_list = []

    for c, k, fb, lw in zip(currents_sorted, couplings_sorted, feedback_sorted, linewidth_sorted):
        psd_filename = get_psd_filename(c, k)
        psd_path = os.path.join(folder, psd_filename)

        if not os.path.isfile(psd_path):
            fallback_filename = f"psd_current_{int(c)}mA_coupling_{k:.6e}.csv" if float(c).is_integer() else psd_filename
            psd_path = os.path.join(folder, fallback_filename)

        if not os.path.isfile(psd_path):
            print(f"  Skipping (file not found): {psd_filename}")
            continue

        freq_raw, power_raw = load_psd_raw(psd_path)
        if len(freq_raw) < 10:
            continue

        offsets_GHz = (freq_raw - absolute_zero_freq) * to_GHz

        power_interp_dB = np.interp(
            freq_offset_GHz,
            offsets_GHz,
            power_raw,
            left=np.nan,
            right=np.nan
        )

        psd_columns_dB.append(power_interp_dB)
        valid_fb_list.append(fb)
        valid_lw_list.append(lw)

    if len(psd_columns_dB) == 0:
        raise RuntimeError("No PSD files could be loaded.")

    psd_dB_array = np.array(psd_columns_dB).T  # Shape: (n_freq, n_runs)
    valid_fb_array = np.array(valid_fb_list)
    valid_lw_array = np.array(valid_lw_list)

    return freq_offset_GHz, valid_fb_array, valid_lw_array, psd_dB_array


def save_processed_data(filepath, freq_offset_GHz, feedback_sorted, linewidth_sorted, psd_dB_array):
    """Save processed data and summary metrics to a .npz file for fast re-plotting."""
    np.savez_compressed(
        filepath,
        freq_offset_GHz=freq_offset_GHz,
        feedback_sorted=feedback_sorted,
        linewidth_sorted=linewidth_sorted,
        psd_dB_array=psd_dB_array
    )
    print(f"Saved processed data to: {filepath}")


def load_processed_data(filepath):
    """Load processed data and summary metrics from a .npz file."""
    data = np.load(filepath)
    freq_offset_GHz = data["freq_offset_GHz"]
    feedback_sorted = data["feedback_sorted"]
    linewidth_sorted = data["linewidth_sorted"]
    psd_dB_array = data["psd_dB_array"]
    print(f"Loaded processed data from: {filepath}")
    return freq_offset_GHz, feedback_sorted, linewidth_sorted, psd_dB_array


def make_plot(freq_offset_GHz, feedback_sorted, linewidth_sorted, folder, 
              psd_dB_array, freq_range_ghz=0.5, max_feedback_db=-47.0):
    """Generate pixel-aligned 2-panel plot."""
    
    fig, (ax_top, ax_bottom) = plt.subplots(
        2, 1, 
        figsize=(10, 8.5), 
        sharex=True, 
        gridspec_kw={'height_ratios': [1, 2.2]}
    )

    x_min = feedback_sorted[-1] if feedback_sorted[0] < feedback_sorted[-1] else feedback_sorted[0]
    x_max = max_feedback_db

    # ------------------------------------------------------------------
    # TOP PANEL: Linewidth vs. Feedback
    # ------------------------------------------------------------------
    ax_top.plot(feedback_sorted, linewidth_sorted, "o-", color="cyan", markersize=4, linewidth=1.2)
    ax_top.set_ylabel("Linewidth (MHz)", fontsize=11)
    ax_top.set_yscale("log")
    ax_top.set_title("Laser Dynamics vs. Feedback Strength", fontsize=13)
    ax_top.grid(True, which="both", linestyle="--", alpha=0.4)
    ax_top.set_facecolor("#0f0f0f")

    # ------------------------------------------------------------------
    # BOTTOM PANEL: PSD Heatmap
    # ------------------------------------------------------------------
    X, Y = np.meshgrid(feedback_sorted, freq_offset_GHz)

    global_max_dB = np.nanmax(psd_dB_array)
    psd_rel_dB = psd_dB_array - global_max_dB

    pcm = ax_bottom.pcolormesh(
        X, Y, psd_rel_dB,
        cmap="inferno",
        shading="auto",
        vmin=-50, vmax=0,
        rasterized=True
    )

    ax_bottom.set_xlabel("Feedback strength (dB)", fontsize=12)
    ax_bottom.set_ylabel("Frequency offset (GHz)", fontsize=12)
    ax_bottom.set_ylim(-freq_range_ghz, freq_range_ghz)
    ax_bottom.set_facecolor("black")

    # Enforce matching bounds
    ax_top.set_xlim(x_max, x_min)
    ax_bottom.set_xlim(x_max, x_min)

    # Perfect horizontal alignment with Divider
    divider_bottom = make_axes_locatable(ax_bottom)
    cax = divider_bottom.append_axes("right", size="2.5%", pad=0.15)
    cbar = fig.colorbar(pcm, cax=cax, label="Relative Intensity (dB)")

    divider_top = make_axes_locatable(ax_top)
    cax_top = divider_top.append_axes("right", size="2.5%", pad=0.15)
    cax_top.axis("off")

    plt.tight_layout()

    output_path = os.path.join(folder, "linewidth_and_psd_coarse.png")
    plt.savefig(output_path, dpi=250, bbox_inches="tight")
    plt.close()
    print(f"Saved 2-panel plot: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot Linewidth and PSD vs feedback strength.")
    parser.add_argument("folder", nargs="?",
                        default=r"C:\Users\josep\Documents\MRes mini-project 2\Figures\coherence_collapse\Official",
                        help="Folder containing the CSV files")
    parser.add_argument("--freq_range_ghz", type=float, default=0.5,
                        help="Frequency offset range +/- GHz for plot (default: 0.5 GHz)")
    parser.add_argument("--max_feedback_db", type=float, default=-47.0,
                        help="Cutoff limit for feedback strength on right x-axis (default: -47.0 dB)")
    parser.add_argument("--n_points", type=int, default=400,
                        help="Number of frequency grid bins (default: 400 for less averaging)")
    parser.add_argument("--replot", action="store_true",
                        help="Skip CSV loading; re-plot from saved .npz file")

    args = parser.parse_args()
    folder = args.folder
    npz_path = os.path.join(folder, "linewidth_and_psd_coarse.npz")

    if args.replot:
        if not os.path.isfile(npz_path):
            raise FileNotFoundError(
                f"No saved data found at {npz_path}. Run without --replot first.")
        freq_offset_GHz, feedback_sorted, linewidth_sorted, psd_dB_array = load_processed_data(npz_path)
    else:
        freq_offset_GHz, feedback_sorted, linewidth_sorted, psd_dB_array = process_data(
            folder, freq_range_ghz=args.freq_range_ghz, max_feedback_db=args.max_feedback_db, n_points=args.n_points
        )
        save_processed_data(npz_path, freq_offset_GHz, feedback_sorted, linewidth_sorted, psd_dB_array)

    make_plot(freq_offset_GHz, feedback_sorted, linewidth_sorted, folder,
              psd_dB_array, freq_range_ghz=args.freq_range_ghz, 
              max_feedback_db=args.max_feedback_db)


if __name__ == "__main__":
    main()